title: TYLER IKEN
author: Tyler Iken
description: > # this means to ignore newlines until "show_excerpts:"
  Personal and professional website to host my research and projects. Please contact me through
  my email at tyleriken@proton.me.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/t-j-iken" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
